"""add kudago events cache

Revision ID: d874ff93fbdf
Revises: 0011
Create Date: 2026-04-13 13:27:12.482596+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd874ff93fbdf'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kudago_events_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kudago_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('short_title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('age_restriction', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('site_url', sa.String(length=1000), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('all_dates', sa.Text(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('place_title', sa.String(length=500), nullable=True),
    sa.Column('place_address', sa.String(length=500), nullable=True),
    sa.Column('place_phone', sa.String(length=100), nullable=True),
    sa.Column('place_subway', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kudago_events_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kudago_events_cache_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kudago_events_cache_kudago_id'), ['kudago_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_kudago_events_cache_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_kudago_events_cache_start_ts'), ['start_ts'], unique=False)

    # event_attendees / events changes are SQLite-only diffs — skip for PostgreSQL compatibility

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kudago_events_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kudago_events_cache_start_ts'))
        batch_op.drop_index(batch_op.f('ix_kudago_events_cache_location'))
        batch_op.drop_index(batch_op.f('ix_kudago_events_cache_kudago_id'))
        batch_op.drop_index(batch_op.f('ix_kudago_events_cache_id'))

    op.drop_table('kudago_events_cache')
    # ### end Alembic commands ###
