"""chat_reactions_token_revocations

Revision ID: c73422c72c51
Revises: f9b3c5d27e84
Create Date: 2026-04-20 14:32:50.206866+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c73422c72c51'
down_revision: Union[str, None] = 'f9b3c5d27e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using='CASE WHEN user_id ~ \'^[0-9]+$\' THEN user_id::integer ELSE NULL END')
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # Обнуляем user_id которые не ссылаются на реального пользователя
    op.execute("UPDATE chat_messages SET user_id = NULL WHERE user_id IS NOT NULL AND user_id NOT IN (SELECT id FROM users)")

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key('chat_messages_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('entity_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_embeddings_type')
        batch_op.create_index(batch_op.f('ix_entity_embeddings_entity_type'), ['entity_type'], unique=False)

    op.execute("UPDATE event_attendees SET created_at = NOW() WHERE created_at IS NULL")

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_event_attendees_event_id'), ['event_id'], unique=False)
        batch_op.create_unique_constraint('uq_event_user', ['event_id', 'user_id'])
        batch_op.drop_constraint('event_attendees_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_parties', schema=None) as batch_op:
        batch_op.drop_index('ix_event_parties_created_at')
        batch_op.drop_index('ix_event_parties_description_trgm', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_event_parties_title_trgm', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # Удаляем реакции с несуществующими user_id до типового cast
    op.execute("DELETE FROM message_reactions WHERE user_id NOT IN (SELECT id::text FROM users)")

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
        batch_op.drop_constraint('message_reactions_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('party_meeting_plan_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('party_meeting_plan_history_changed_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['changed_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('party_meeting_plans', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('party_meeting_plans_updated_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.drop_index('ix_rec_impressions_target')
        batch_op.drop_index('ix_rec_impressions_user_type_created')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('banned_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('muted_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('muted_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('banned_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.create_index('ix_rec_impressions_user_type_created', ['user_id', 'rec_type', 'created_at'], unique=False)
        batch_op.create_index('ix_rec_impressions_target', ['rec_type', 'target_id'], unique=False)

    with op.batch_alter_table('party_meeting_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('party_meeting_plans_updated_by_fkey', 'users', ['updated_by'], ['id'])
        batch_op.alter_column('updated_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('party_meeting_plan_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('party_meeting_plan_history_changed_by_fkey', 'users', ['changed_by'], ['id'])
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_reactions_message_id_fkey', 'chat_messages', ['message_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('event_parties', schema=None) as batch_op:
        batch_op.create_index('ix_event_parties_title_trgm', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('ix_event_parties_description_trgm', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('ix_event_parties_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_attendees_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_event_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_event_attendees_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('entity_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_embeddings_entity_type'))
        batch_op.create_index('ix_entity_embeddings_type', ['entity_type'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
